// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82OAYySw7Tyw8YWNS9yaQE7yAD2a7amc',
    appId: '1:949425567081:web:bf1bec0ad37c6acda739f8',
    messagingSenderId: '949425567081',
    projectId: 'bookmate-ec92e',
    authDomain: 'bookmate-ec92e.firebaseapp.com',
    databaseURL: 'https://bookmate-ec92e-default-rtdb.firebaseio.com',
    storageBucket: 'bookmate-ec92e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHDM6zM6EZxrcP3KdtVoF2bV7nHm6W1ow',
    appId: '1:949425567081:ios:4a7eea221c872684a739f8',
    messagingSenderId: '949425567081',
    projectId: 'bookmate-ec92e',
    databaseURL: 'https://bookmate-ec92e-default-rtdb.firebaseio.com',
    storageBucket: 'bookmate-ec92e.firebasestorage.app',
    iosBundleId: 'com.bekirmese.bookMate',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuMPUQEUBiqOjR95ckxjUzMkZ8_UGniI',
    appId: '1:949425567081:android:696884fb0e0dcf8ca739f8',
    messagingSenderId: '949425567081',
    projectId: 'bookmate-ec92e',
    databaseURL: 'https://bookmate-ec92e-default-rtdb.firebaseio.com',
    storageBucket: 'bookmate-ec92e.firebasestorage.app',
  );

}